# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='todo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
