# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20151230_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.CharField(default=b'Pending', max_length=200),
        ),
    ]
